---
#
# Defaults for role newrelic-infra-unizin
#

NEWRELIC_DEBIAN_REPO: "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt {{ ansible_lsb.codename }} main"
NEWRELIC_DEBIAN_KEY_ID: '548C16BF'
NEWRELIC_DEBIAN_KEY_URL: 'https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg'

NEWRELIC_CONFIG_PATH: "/etc/newrelic-infra.yml"

nrinfragent_version: "*"

#
# OS packages
#

NEWRELIC_DEBIAN_PKG: "newrelic-infra{{ nrinfragent_version }}"

