---
#
# Defaults for role provison
# 
pem_file: openedx-staging
instance: t2.small
app_instance: t2.medium
common_instance: t2.large
ami: ami-1c256f0a
sg_prefix: "Open-edX-Unizin2-Security"
edxapp_sg: "{{ sg_prefix }}-AppSG-HWXS0HQOJ3FR"
mongo_sg: "{{ sg_prefix }}-MongoSG-J28EO12TBO6K"
common_sg: "{{ sg_prefix }}-CommonSG-EQIF8V9FF6Y3"
instance_region: us-east-1
subnet: subnet-99fa96ee
tag_app: "openedx-{{ name }}-app"
tag_pmongo: "openedx-{{ name}}-mongo-1"
tag_smongo: "openedx-{{ name }}-mongo-2"
tag_rabbit: "openedx-{{ name }}-common"
...
