---
# Tasks for role create_rds
#
- name: Launch RDS Instance
  rds:
     command: create
     instance_name: "{{ rds_instance_name }}"
     db_engine: MySQL
     size: "{{ db_size }}"
     instance_type: "{{ db_instance_type }}"
     username: "{{ rds_master_user }}"
     password: "{{ rds_master_password }}"
     region: "{{ rds_region }}"
     vpc_security_groups: "{{ rds_vpc_sg }}"
     publicly_accessible: no
     zone: "{{ rds_zone }}"
     tags:
       Environment: "{{ tag_environment }}" 
       Application: "{{ tag_application }}"
...
