---

rdsUser: "{{ lookup('env','MYSQL_ADMIN_USER') }}"
rdsPass: "{{ lookup('env','MYSQL_ADMIN_PASSWORD') }}"

edxRdsHost: "{{ lookup('env','RDS') }}"

COMMON_MYSQL_MIGRATE_USER: "{{ lookup('env','COMMON_MYSQL_MIGRATE_USER') }}"
COMMON_MYSQL_MIGRATE_PASS: "{{ lookup('env','COMMON_MYSQL_MIGRATE_PASS') }}"

COMMON_MYSQL_READ_ONLY_USER: 'read_only'
COMMON_MYSQL_READ_ONLY_PASS: "{{ lookup('env','COMMON_MYSQL_READ_ONLY_PASS') }}"

COMMON_MYSQL_ADMIN_USER: 'admin'
COMMON_MYSQL_ADMIN_PASS: "{{ lookup('env','COMMON_MYSQL_ADMIN_PASS') }}"

EDXAPP_MYSQL_PASSWORD: "{{ lookup('env','EDXAPP_MYSQL_PASSWORD') }}"
EDXAPP_MYSQL_CSMH_PASSWORD: "{{ EDXAPP_MYSQL_PASSWORD }}"
XQUEUE_MYSQL_PASSWORD: "{{ lookup('env','XQUEUE_MYSQL_PASSWORD') }}"

edxlocal_databases:
  - "{{ ECOMMERCE_DEFAULT_DB_NAME | default('ecommerce') }}"
  - "{{ INSIGHTS_DATABASE_NAME | default('dashboard') }}"
  - "{{ XQUEUE_MYSQL_DB_NAME | default('xqueue') }}"
  - "{{ EDXAPP_MYSQL_DB_NAME | default('edxapp') }}"
  - "{{ EDXAPP_MYSQL_CSMH_DB_NAME | default('edxapp_csmh') }}"
  - "{{ EDX_NOTES_API_MYSQL_DB_NAME | default('edx-notes-api') }}"
  - "{{ PROGRAMS_DEFAULT_DB_NAME | default('programs') }}"
  - "{{ ANALYTICS_API_DEFAULT_DB_NAME | default('analytics-api') }}"
  - "{{ ANALYTICS_API_REPORTS_DB_NAME | default('reports') }}"
  - "{{ CREDENTIALS_DEFAULT_DB_NAME | default('credentials') }}"
  - "{{ DISCOVERY_DEFAULT_DB_NAME | default('discovery') }}"

edxlocal_database_users:
  - {
      db: "{{ ECOMMERCE_DEFAULT_DB_NAME | default('ecommerce') }}",
      user: "{{ ECOMMERCE_DATABASE_USER | default('ecomm001') }}",
      pass: "{{ ECOMMERCE_DATABASE_PASSWORD | default('password') }}"
    }
  - {
      db: "{{ INSIGHTS_DATABASE_NAME | default('dashboard') }}",
      user: "{{ INSIGHTS_MYSQL_USER | default('rosencrantz') }}",
      pass: "{{ INSIGHTS_MYSQL_USER | default('secret') }}"
    }
  - {
      db: "{{ XQUEUE_MYSQL_DB_NAME | default('xqueue') }}",
      user: "{{ XQUEUE_MYSQL_USER | default('xqueue001') }}",
      pass: "{{ XQUEUE_MYSQL_PASSWORD | default('password') }}"
    }

  - {
      db: "{{ EDXAPP_MYSQL_DB_NAME | default('edxapp') }}",
      user: "{{ EDXAPP_MYSQL_USER | default('edxapp001') }}",
      pass: "{{ EDXAPP_MYSQL_PASSWORD | default('password') }}"
    }

  - {
      db: "{{ EDXAPP_MYSQL_CSMH_DB_NAME | default('edxapp_csmh') }}",
      user: "{{ EDXAPP_MYSQL_CSMH_USER | default('edxapp001') }}",
      pass: "{{ EDXAPP_MYSQL_CSMH_PASSWORD | default('password') }}"
    }
  - {
      db: "{{ PROGRAMS_DEFAULT_DB_NAME | default('programs') }}",
      user: "{{ PROGRAMS_DATABASE_USER | default('programs001') }}",
      pass: "{{ PROGRAMS_DATABASE_PASSWORD | default('password') }}"
    }
  - {
      db: "{{ ANALYTICS_PIPELINE_OUTPUT_DATABASE_NAME | default('reports001') }}",
      user: "{{ ANALYTICS_PIPELINE_OUTPUT_DATABASE_USER | default('pipeline001') }}",
      pass: "{{ ANALYTICS_PIPELINE_OUTPUT_DATABASE_PASSWORD | default('password') }}"
    }
  - {
      db: "{{ HIVE_METASTORE_DATABASE_NAME | default('edx_hive_metastore') }}",
      user: "{{ HIVE_METASTORE_DATABASE_USER | default('edx_hive') }}",
      pass: "{{ HIVE_METASTORE_DATABASE_PASSWORD | default('edx') }}"
    }
  - {
      db: "{{ CREDENTIALS_DEFAULT_DB_NAME | default('credentials') }}",
      user: "{{ CREDENTIALS_MYSQL_USER | default('credentials001') }}",
      pass: "{{ CREDENTIALS_MYSQL_PASSWORD | default('password') }}"
    }
  - {
      db: "{{ DISCOVERY_DEFAULT_DB_NAME | default('discovery') }}",
      user: "{{ DISCOVERY_MYSQL_USER | default('discov001') }}",
      pass: "{{ DISCOVERY_MYSQL_PASSWORD | default('password') }}"
    }
...
