
# Security Group paraneters for Michigan Open edX instance

sg_prefix: "Open-edX-Unizin-Security"
edxapp_sg: "{{ sg_prefix }}-AppSG-1EMWALD8F7RX2"
mongo_sg: "{{ sg_prefix }}-MongoSG-Y4H5UD662D25"
common_sg: "{{ sg_prefix }}-CommonSG-OBXTYSWM1W0F"

rds_vpc_sg: sg-714a400f
