
# Security Group paraneters for Michigan Open edX instance

build_sg: sg-d94f18a8
full_name: Michigan
DOMAIN: openedx-umich2.testing.unizin.org
PREVIEWURL: openedx-preview-umich2.testing.unizin.org
S3STORAGEBUCKET: unizin-openedx-umich

EDXAPP_AWS_ACCESS_KEY_ID: AKIAIBKWGLRTNMLPBVVA
EDXAPP_AWS_SECRET_ACCESS_KEY: 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

EMAIL_HOST_USER: michael.steiner
EMAIL_HOST_PASSWORD: tr^Y+filUCr4571l
