
# Open edX ansible/cloudformation build paraneters for Unizin2 Open edX instance

build_sg: sg-f6c7f487
full_name: Unizin2

vpc: vpc-42840a25
base_ami: ami-b5eee6ce

EDXAPP_AWS_ACCESS_KEY_ID: AKIAJKFW3GCONS3OMTKQ
EDXAPP_AWS_SECRET_ACCESS_KEY: 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

EMAIL_HOST_USER: michael.steiner
EMAIL_HOST_PASSWORD: tr^Y+filUCr4571l

hosted_zone_minus_period: testing.unizin.org
hosted_zone_name: "{{ hosted_zone_minus_period }}."

NEWRELIC_LICENSE_KEY: 9de377b20faec94d4116a5bd10bb42ac8eba571d

# MySQL
MYSQL_ADMIN_USER: 'root'
MYSQL_ADMIN_PASSWORD: 'V8vysW5JFsE29WLjx'

COMMON_MYSQL_MIGRATE_USER: 'migrate'
COMMON_MYSQL_MIGRATE_PASS: 'u2W36Kb8M7YGyniTW'

COMMON_MYSQL_ADMIN_PASS: 'JCVdM7MaxbaK2RutX'
COMMON_MYSQL_READ_ONLY_PASS: 'xUA77UxovUq5A2Giq'

EDXAPP_MYSQL_PASSWORD: '7GPZNdaXwh7nRBy2o'
EDXAPP_MYSQL_PASSWORD_READ_ONLY: 'KXG9k9A2HjqPoTWDY'
EDXAPP_MYSQL_PASSWORD_ADMIN: "{{ MYSQL_ADMIN_PASSWORD }}"

XQUEUE_MYSQL_PASSWORD: 'UugvnUkJiS2NNYAHn'

# MongoDB
MONGO_ADMIN_PASSWORD: 'UV9FQAFypXFxHMahs'
EDXAPP_MONGO_PASSWORD: 'iLwX42e6KCYbhNG5ch'
FORUM_MONGO_PASSWORD: 'njkb28ZY87PbMZ3Rd'

