
# Security Group paraneters for Unizin Open edX instance

sg_prefix: "Open-edX-Unizin-Security"
edxapp_sg: "{{ sg_prefix }}-AppSG-CTG8PKB1VZF1"
mongo_sg: "{{ sg_prefix }}-MongoSG-34V0MYUM14H1"
common_sg: "{{ sg_prefix }}-CommonSG-D2U9CADY20LH"

rds_vpc_sg: sg-e195a99f
